In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_excel("data/TweetClassification-Summary.xlsx")

In [22]:
df

,#,type,text,aggregatedAnnotation,aggregatedAnnotationConfidence,annotator1,annotator2,annotator3
0,1,TWEET,مبروك و سامحونا لعجزنا التام. عقبال اللي جوه. ...,0,0.6667,-1,0,0
1,2,C1,كلنا بره ومش هنبطل نزايد على العجايز الي جابون...,-1,0.6667,-1,-1,0
2,3,C2,بدل ما انت قاعد بره كده تعالي ازرع الصحرا,0,1.0000,0,0,0
3,4,C3,قذر اتفووو ماتيجى مصر وتورينا نفسك كدا ياجبان,-1,1.0000,-1,-1,-1
4,5,C4,وهكذا رجال الشو اللي محرومين من عمل برنامج الغ...,-1,0.6667,-1,-1,0
...,...,...,...,...,...,...,...,...
1095,1096,C6,أستاذنا العزيز بلال فضل يحزنني أن يتم حذف حلقا...,0,1.0000,0,0,0
1096,1097,C7,،برنامج يدعو للتفكير أكيد يمنعوه لأنهم خوافون ...,0,1.0000,0,0,0
1097,1098,C8,"""#أزهى_عصور_المسخره هل ضيعت ""شيما"" محافظ بورس...",-1,0.6923,-1,0,-1
1098,1099,C9,الله يلعنك و يلعن اللى جابوك يا رمه جايفه,-2,1.0000,-2,-2,-2
1099,1100,C10,أنت رجل حيوان,-2,0.6923,-2,-1,-2

In [23]:

# Extraire les colonnes "Text" et "Toxic/Not Toxic"
df1 = df[['text', 'aggregatedAnnotation']]
df1

                                                   text  aggregatedAnnotation
0     مبروك و سامحونا لعجزنا التام. عقبال اللي جوه. ...                     0
1     كلنا بره ومش هنبطل نزايد على العجايز الي جابون...                    -1
2             بدل ما انت قاعد بره كده تعالي ازرع الصحرا                     0
3         قذر اتفووو ماتيجى مصر وتورينا نفسك كدا ياجبان                    -1
4     وهكذا رجال الشو اللي محرومين من عمل برنامج الغ...                    -1
...                                                 ...                   ...
1095  أستاذنا العزيز بلال فضل يحزنني أن يتم حذف حلقا...                     0
1096  ،برنامج يدعو للتفكير أكيد يمنعوه لأنهم خوافون ...                     0
1097  "#أزهى_عصور_المسخره  هل ضيعت "شيما" محافظ بورس...                    -1
1098          الله يلعنك و يلعن اللى جابوك يا رمه جايفه                    -2
1099                                      أنت رجل حيوان                    -2

[1100 rows x 2 columns]

In [26]:

df_clean = df1.rename(columns={'aggregatedAnnotation': 'Toxic/Not Toxic' , 'text': 'Text'})

df_clean

                                                   Text  Toxic/Not Toxic
0     مبروك و سامحونا لعجزنا التام. عقبال اللي جوه. ...                0
1     كلنا بره ومش هنبطل نزايد على العجايز الي جابون...               -1
2             بدل ما انت قاعد بره كده تعالي ازرع الصحرا                0
3         قذر اتفووو ماتيجى مصر وتورينا نفسك كدا ياجبان               -1
4     وهكذا رجال الشو اللي محرومين من عمل برنامج الغ...               -1
...                                                 ...              ...
1095  أستاذنا العزيز بلال فضل يحزنني أن يتم حذف حلقا...                0
1096  ،برنامج يدعو للتفكير أكيد يمنعوه لأنهم خوافون ...                0
1097  "#أزهى_عصور_المسخره  هل ضيعت "شيما" محافظ بورس...               -1
1098          الله يلعنك و يلعن اللى جابوك يا رمه جايفه               -2
1099                                      أنت رجل حيوان               -2

[1100 rows x 2 columns]

In [27]:
# Remplacer les valeurs "Toxic" par 1 et "Not Toxic" par 0
df_clean['Toxic/Not Toxic'] = df_clean['Toxic/Not Toxic'].apply(lambda x: 0 if x == 0 else 1)

In [28]:
df_clean

                                                   Text  Toxic/Not Toxic
0     مبروك و سامحونا لعجزنا التام. عقبال اللي جوه. ...                0
1     كلنا بره ومش هنبطل نزايد على العجايز الي جابون...                1
2             بدل ما انت قاعد بره كده تعالي ازرع الصحرا                0
3         قذر اتفووو ماتيجى مصر وتورينا نفسك كدا ياجبان                1
4     وهكذا رجال الشو اللي محرومين من عمل برنامج الغ...                1
...                                                 ...              ...
1095  أستاذنا العزيز بلال فضل يحزنني أن يتم حذف حلقا...                0
1096  ،برنامج يدعو للتفكير أكيد يمنعوه لأنهم خوافون ...                0
1097  "#أزهى_عصور_المسخره  هل ضيعت "شيما" محافظ بورس...                1
1098          الله يلعنك و يلعن اللى جابوك يا رمه جايفه                1
1099                                      أنت رجل حيوان                1

[1100 rows x 2 columns]

In [29]:
# Get the unique values in 'column1'
unique_values = df_clean['Toxic/Not Toxic'].unique()

# Print the unique values
print("Unique values in column1:", unique_values)

Unique values in column1: [0 1]

In [30]:
num_toxic = df_clean['Toxic/Not Toxic'].value_counts()[1]
print(f"Il y a {num_toxic} lignes étiquetées comme toxiques.")
num_toxic = df_clean['Toxic/Not Toxic'].value_counts()[0]
print(f"Il y a {num_toxic} lignes étiquetées comme non toxiques.")

Il y a 647 lignes étiquetées comme toxiques.
Il y a 453 lignes étiquetées comme non toxiques.

In [31]:
# Enregistrer la dataframe nettoyée dans un fichier CSV
df_clean.to_csv('clean/TweetClassification-Summary_nettoye.csv', index=False)